CREATE TABLE [dbo].[dim_date] (

	[sk_date] int NOT NULL, 
	[date] date NOT NULL, 
	[day] int NOT NULL, 
	[day_suffix] char(2) NOT NULL, 
	[week_day] int NOT NULL, 
	[week_day_name] varchar(10) NOT NULL, 
	[week_day_name_short] char(3) NOT NULL, 
	[week_day_name_first_letter] char(1) NOT NULL, 
	[DOW_in_month] int NOT NULL, 
	[day_of_year] smallint NOT NULL, 
	[week_of_month] int NOT NULL, 
	[week_of_year] int NOT NULL, 
	[month] int NOT NULL, 
	[month_name] varchar(10) NOT NULL, 
	[month_name_short] char(3) NOT NULL, 
	[month_name_first_letter] char(1) NOT NULL, 
	[quarter] int NOT NULL, 
	[quarter_name] varchar(6) NOT NULL, 
	[year] int NOT NULL, 
	[MMYYYY] char(6) NOT NULL, 
	[month_year] char(7) NOT NULL, 
	[is_weekend] bit NOT NULL, 
	[is_holiday] bit NOT NULL, 
	[holiday_name] varchar(20) NULL, 
	[special_days] varchar(20) NULL, 
	[financial_year] int NULL, 
	[financial_quarter] int NULL, 
	[financial_month] int NULL, 
	[first_date_of_year] date NULL, 
	[last_date_of_year] date NULL, 
	[first_date_of_quarter] date NULL, 
	[last_date_of_quarter] date NULL, 
	[first_date_of_month] date NULL, 
	[last_date_of_month] date NULL, 
	[first_date_of_week] date NULL, 
	[last_date_of_week] date NULL, 
	[current_year] smallint NULL, 
	[current_quarter] smallint NULL, 
	[current_month] smallint NULL, 
	[current_week] smallint NULL, 
	[current_day] smallint NULL
);